#pragma once

#include <cstdint>

enum class TileType : std::uint8_t
{
    Empty = 0,
    Path_North,
    Path_East,
    Path_NorthEast,
    Path_South,
    Path_NorthSouth,
    Path_EastSouth,
    Path_NorthEastSouth,
    Path_West,
    Path_NorthWest,
    Path_EastWest,
    Path_NorthEastWest,
    Path_SouthWest,
    Path_NorthSouthWest,
    Path_EastSouthWest,
    Path_NorthEastSouthWest,
    Wall,
    Wall_ConcaveCorner_SouthEast,
    Wall_ConcaveCorner_SouthWest,
    Wall_ConcaveCorner_NorthWest,
    Wall_ConcaveCorner_NorthEast,
    Wall_Edge_East,
    Wall_Edge_South,
    Wall_Edge_West,
    Wall_Edge_North,
    Wall_ConvexCorner_SouthEast,
    Wall_ConvexCorner_SouthWest,
    Wall_ConvexCorner_NorthWest,
    Wall_ConvexCorner_NorthEast,
    Wall2,
    Wall2_North,
    Wall2_East,
    Wall2_NorthEast,
    Wall2_South,
    Wall2_NorthSouth,
    Wall2_EastSouth,
    Wall2_NorthEastSouth,
    Wall2_West,
    Wall2_NorthWest,
    Wall2_EastWest,
    Wall2_NorthEastWest,
    Wall2_SouthWest,
    Wall2_NorthSouthWest,
    Wall2_EastSouthWest,
    Wall2_NorthEastSouthWest,
    // Door_North,
    // Door_East,
    // Door_NorthEast,
    // Door_South,
    Door_NorthSouth,
    // Door_EastSouth,
    // Door_NorthEastSouth,
    // Door_West,
    // Door_NorthWest,
    Door_EastWest,
    // Door_NorthEastWest,
    // Door_SouthWest,
    // Door_NorthSouthWest,
    // Door_EastSouthWest,
    // Door_NorthEastSouthWest,
    Pellet,
    PowerPellet,
    PlayerSpawn,
    GhostSpawn,
    BonusSpawn,
    ReadySpawn,
    Tunnel
};
